### ISSUE TITLE
Seems that Ulysses.js does not work?

### ISSUE THREAD

**Issue by 56DOlL** [langkhach270389/Scripting#2]
Thanks for your great work. 

Could you please detail how to activate the subscription of Ulysses?

I set it up on my phone, but it does not work. Look into the Quantumult Activity panel, does not see any request hit the rewrite rule.

**Comment by oldzhg** [comment]
It doesn't seem to work anymore.

**Comment by langkhach270389** [comment]
> It doesn't seem to work anymore.

Okay. Ulysses not working. Deleted
