### ISSUE TITLE
Grammarly needed

### ISSUE THREAD

**Issue by ackurdeeve** [langkhach270389/Scripting#6]
Grammarly Keyboard by Grammarly, Inc https://apps.apple.com/us/app/grammarly-keyboard/id1158877342

I think the auth flow is as same as https://app.grammarly.com/

A great app for English writing

**Comment by langkhach270389** [comment]
grammarly unlocked

**Comment by ackurdeeve** [comment]
Let me test it. Thanks

**Comment by ackurdeeve** [comment]
The advanced  features are not actually unlocked i think.

**Comment by langkhach270389** [comment]
@ackurdeeve Okay. Fix later

**Comment by ackurdeeve** [comment]
@langkhach270389 please let me know if it is solved. Good luck.

**Comment by langkhach270389** [comment]
@ackurdeeve Okay
