### ISSUE TITLE
sleep cycle needed

### ISSUE THREAD

**Issue by kpictor** [langkhach270389/Scripting#7]
hey brother,can you.try to brack this app https://apps.apple.com/us/app/sleep-cycle-smart-alarm-clock/id320606217 
this app can help us sleep better and get a beautiful chart and statistics
need your help:)

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by langkhach270389** [comment]
like sleepzy. sleepzy unlocked. 
sleep cycle. try later

**Comment by kpictor** [comment]
okay this day I try both two app and find sleep cycle can measure more right... any way, thx!
